### ISSUE TITLE
still gray screan....

### ISSUE THREAD

**Issue by p3im4n** [Ansh-Rathod/Flutter-Photoarc-app#3]
hi dear @Ansh-Rathod 
I tested my backend with postman successfully
but in my app, after clicking on the "authenticate" button, the app stuck on a gray screen
after debugging with android studio I saw these error on console:

```

======== Exception caught by widgets library =======================================================
The following StateError was thrown building InheritedProvider<CurrentUserCubit>:
Bad state: Tried to read a provider that threw during the creation of its value.
The exception occurred during the creation of type CurrentUserCubit.


══╡ EXCEPTION CAUGHT BY PROVIDER ╞═══════════════════════════════
The following _CastError was thrown:
Null check operator used on a null value

When the exception was thrown, this was the stack:
#0      _BottomNavBarState.build.<anonymous closure> (package:social_media/screens/bottom_nav_bar/bottom_nav_bar.dart:52:59)
#1      _CreateInheritedProviderState.value (package:provider/src/inherited_provider.dart:729:36)
#2      _InheritedProviderScopeElement.value (package:provider/src/inherited_provider.dart:583:33)
#3      Provider.of (package:provider/src/provider.dart:303:37)
#4      ReadContext.read (package:provider/src/provider.dart:656:21)
#5      _BlocBuilderBaseState.initState (package:flutter_bloc/src/bloc_builder.dart:129:36)
#6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4805:57)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)

 
```

I debug the flutter project with the emulator for hours and I believe that the problem is firebase!!!
in these lines:
 
```
 return BlocProvider(
      create: (context) => CurrentUserCubit()
        ..setCurrentUser(FirebaseAuth.instance.currentUser!.uid),
      child: BlocBuilder<CurrentUserCubit, CurrentUserState>(
```
 

currentUser is always null, also CurrentUserCubit and CurrentUserState have not correct data, and it leads to an exception 

how should I configure my firebase settings?
 best regards,
peiman sh

**Comment by p3im4n** [comment]
ok....
there was some stuff to do about firebase
I read these pages:
https://firebase.google.com/docs/android/setup
 https://firebase.google.com/docs/auth/android/email-link-auth
https://firebase.google.com/docs/auth/android/password-auth
https://firebase.google.com/docs/auth/android/email-link-auth?authuser=0
and more....
I close this thread
